### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by 5b21r** [IgnacioPinedo/checklist-app#7]
# Is it possible to make the URL of the checklist to reflect on the name of the Checklist?

Exemple:

Instead of
_https://checklister-app.netlify.app/checklists/e3cf2acd-f7f5-4b82-a877-c8d77575ce2b_ 

the URL would be
_**https://checklister-app.netlify.app/checklists/ChecklistName**_

**Comment by IgnacioPinedo** [comment]
Using the checklist name might not be good when following web standards, what we can do instead is create a slug for the checklist.

```
A URL slug is the last part of a [URL](https://www.semrush.com/blog/what-is-a-url/) address that serves as a unique identifier of the page
```
(Ref: [What Is a Slug?](https://www.semrush.com/blog/what-is-a-url-slug))

So instead of `.../checklists/ChecklistName`, we would have `.../checklists/checklist-name`.

**Comment by 5b21r** [comment]
This is even better! The main point of this feature is to make a clearer URL to make sure which checklist we are using/sharing etc..

#GoForTheSlugs
